# Generated by Django 2.1.7 on 2019-03-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('definition', models.CharField(db_column='definition', max_length=255)),
            ],
            options={
                'verbose_name': 'Stages',
                'verbose_name_plural': 'Stages',
                'db_table': 'Stage',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
