# Generated by Django 2.1.7 on 2019-03-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='definition',
            field=models.CharField(db_column='definition', max_length=1000),
        ),
    ]
