# Generated by Django 2.2.2 on 2019-07-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msystem',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
    ]
