# Generated by Django 2.2.2 on 2019-07-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0002_auto_20190720_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msystem',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=False),
        ),
    ]
