# Generated by Django 2.1.7 on 2019-04-07 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stage', '0001_initial'),
        ('indicator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rules',
                'verbose_name_plural': 'Rules',
                'db_table': 'Rule',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RuleWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(db_column='weight')),
                ('indicator', models.ForeignKey(on_delete=None, to='indicator.Indicator')),
                ('stage', models.ForeignKey(on_delete=None, to='stage.Stage')),
            ],
            options={
                'verbose_name': 'Weights',
                'verbose_name_plural': 'Weights',
                'db_table': 'RuleWeight',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='weights',
            field=models.ManyToManyField(related_name='rule_weights', to='modules.rule.RuleWeight'),
        ),
    ]
