# Generated by Django 2.1.5 on 2019-01-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('email', models.CharField(db_column='email', max_length=255)),
                ('password', models.CharField(db_column='password', max_length=255)),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
                'managed': True,
            },
        ),
    ]
