# Generated by Django 2.2.2 on 2019-12-14 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0004_auto_20190905_2155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('patient', models.ForeignKey(null=True, on_delete=None, to='patient.Patient')),
                ('user', models.ForeignKey(db_column='owner', null=True, on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'periods',
                'verbose_name_plural': 'periods',
                'db_table': 'Period',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
