# Generated by Django 2.2.2 on 2019-12-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='begin',
            field=models.DateField(db_column='begin'),
        ),
        migrations.AlterField(
            model_name='period',
            name='end',
            field=models.DateField(db_column='end'),
        ),
    ]
