# Generated by Django 2.2.2 on 2019-12-14 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0002_auto_20191214_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='user',
            field=models.ForeignKey(db_column='user', null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
