# Generated by Django 2.2.2 on 2020-01-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0004_auto_20191013_2122'),
        ('period', '0003_auto_20191214_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='rule',
            field=models.ForeignKey(db_column='rule', null=True, on_delete=None, to='rule.Rule'),
        ),
    ]
