# Generated by Django 2.2.2 on 2020-01-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0003_auto_20190720_1709'),
        ('period', '0004_period_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='system',
            field=models.ForeignKey(null=True, on_delete=None, to='msystem.MSystem'),
        ),
    ]
