# Generated by Django 2.2.2 on 2019-09-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='initials',
            field=models.CharField(db_column='initials', default='a', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='measurement',
            field=models.CharField(db_column='measurement', default='a', max_length=3),
            preserve_default=False,
        ),
    ]
