# Generated by Django 2.2.2 on 2019-06-16 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_patient_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('patient', models.ForeignKey(null=True, on_delete=None, to='patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.IntegerField(db_column='indicator')),
                ('value', models.DecimalField(db_column='value', decimal_places=2, max_digits=30)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Monitoring')),
            ],
        ),
    ]
