# Generated by Django 2.2.2 on 2019-09-12 22:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0004_auto_20190905_2155'),
        ('msystem', '0003_auto_20190720_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('patient', models.ForeignKey(null=True, on_delete=None, to='patient.Patient')),
                ('system', models.ForeignKey(null=True, on_delete=None, to='msystem.MSystem')),
            ],
            options={
                'verbose_name': 'Monitorings',
                'verbose_name_plural': 'Monitorings',
                'db_table': 'Monitoring',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MonitoringIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.IntegerField(db_column='indicator')),
                ('value', models.DecimalField(db_column='value', decimal_places=2, max_digits=30)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Monitoring')),
            ],
            options={
                'verbose_name': 'Monitoring Indicators',
                'verbose_name_plural': 'Monitoring Indicators',
                'db_table': 'Monitoring_Indicators',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
