# Generated by Django 2.2.2 on 2019-07-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('msystem', '0001_initial'),
        ('monitoring', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=None, to='patient.Patient'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='system',
            field=models.ForeignKey(null=True, on_delete=None, to='msystem.MSystem'),
        ),
    ]
