# Generated by Django 2.2.2 on 2020-01-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20190929_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=None, to='patient.PatientRemoteReference'),
        ),
    ]
