# Generated by Django 2.2.2 on 2020-01-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20200118_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoring',
            old_name='patient',
            new_name='reference',
        ),
    ]
