# Generated by Django 2.2 on 2019-04-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('details', models.CharField(db_column='details', max_length=1000, null=True)),
                ('institutions', models.ManyToManyField(related_name='group_institution', to='institution.Institution')),
            ],
            options={
                'verbose_name': 'Groups',
                'verbose_name_plural': 'Groups',
                'db_table': 'Group',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
