# Generated by Django 2.1.7 on 2019-04-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20190328_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='details',
            field=models.CharField(db_column='details', max_length=1000, null=True),
        ),
    ]
