# Generated by Django 2.1.7 on 2019-03-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_user'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='patients',
            field=models.ManyToManyField(related_name='group_patients', to='patient.Patient'),
        ),
        migrations.AlterField(
            model_name='group',
            name='institutions',
            field=models.ManyToManyField(related_name='group_institution', to='institution.Institution'),
        ),
    ]
