# Generated by Django 2.2.2 on 2019-07-16 01:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stage', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(db_column='first_name', max_length=255)),
                ('last_name', models.CharField(db_column='last_name', max_length=255)),
                ('birth_date', models.DateField(db_column='brith_date')),
                ('gender', models.IntegerField(db_column='gender')),
                ('obs', models.CharField(db_column='obs', max_length=3000, null=True)),
                ('institutions.json', models.ManyToManyField(related_name='user_institution', to='institution.Institution')),
                ('stage', models.ForeignKey(null=True, on_delete=None, to='stage.Stage')),
            ],
            options={
                'verbose_name': 'Patients',
                'verbose_name_plural': 'Patients',
                'db_table': 'Patient',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
