# Generated by Django 2.1.7 on 2019-03-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=255)),
                ('last_name', models.CharField(db_column='last_name', max_length=255)),
                ('birth_date', models.DateField(db_column='brith_date')),
                ('gender', models.IntegerField(db_column='gender')),
                ('obs', models.CharField(db_column='obs', max_length=3000)),
                ('stage', models.ForeignKey(on_delete=None, to='stage.Stage')),
            ],
            options={
                'verbose_name': 'Patients',
                'verbose_name_plural': 'Patients',
                'db_table': 'Patient',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
