# Generated by Django 2.2 on 2019-05-27 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
