# Generated by Django 2.2.2 on 2019-07-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='institutions',
            field=models.ManyToManyField(related_name='patient_institution', to='institution.Institution'),
        ),
    ]
