# Generated by Django 2.1.7 on 2019-03-17 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='obs',
            field=models.CharField(db_column='obs', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=None, to='stage.Stage'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
