# Generated by Django 2.2.2 on 2019-09-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20190721_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(db_column='birth_date'),
        ),
    ]
