# Generated by Django 2.2.2 on 2020-01-16 21:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0003_auto_20190720_1709'),
        ('patient', '0004_auto_20190905_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='uuid',
        ),
        migrations.CreateModel(
            name='PatientRemoteReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('patient', models.ForeignKey(on_delete=None, to='patient.Patient')),
                ('system', models.ForeignKey(on_delete=None, to='msystem.MSystem')),
            ],
            options={
                'verbose_name': 'Patiente Remote Reference',
                'verbose_name_plural': 'Patiente Remote Reference',
                'db_table': 'PatientRemoteReference',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
