# Generated by Django 2.2.2 on 2020-01-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20200116_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientremotereference',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=None, to='patient.Patient'),
        ),
    ]
