# Generated by Django 2.2.2 on 2020-01-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20200116_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientremotereference',
            name='name',
            field=models.CharField(db_column='name', default='', max_length=255),
            preserve_default=False,
        ),
    ]
