# Generated by Django 2.2.2 on 2020-01-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patientremotereference_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientremotereference',
            name='system',
            field=models.ForeignKey(null=True, on_delete=None, to='msystem.MSystem'),
        ),
    ]
