# Generated by Django 2.2.2 on 2019-07-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicator', '0001_initial'),
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='description', max_length=255)),
            ],
            options={
                'verbose_name': 'Recomendations',
                'verbose_name_plural': 'Recomendations',
                'db_table': 'Recomendation',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(db_column='weight')),
                ('indicator', models.ForeignKey(on_delete=None, to='indicator.Indicator')),
                ('recomendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.Recomendation')),
                ('stage', models.ForeignKey(on_delete=None, to='stage.Stage')),
            ],
            options={
                'verbose_name': 'Rules',
                'verbose_name_plural': 'Rules',
                'db_table': 'Rule',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(db_column='quality', max_length=10)),
                ('begin', models.IntegerField(db_column='threshold_begin')),
                ('end', models.IntegerField(db_column='threshold_end')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.Rule')),
            ],
            options={
                'verbose_name': 'Thresholds',
                'verbose_name_plural': 'Thresholds',
                'db_table': 'Threshold',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
