# Generated by Django 2.2 on 2019-04-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stage', '0001_initial'),
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(db_column='quality', max_length=10)),
                ('minimum', models.IntegerField(db_column='minimum')),
                ('maximum', models.IntegerField(db_column='maximum')),
            ],
            options={
                'verbose_name': 'Quality Intervals',
                'verbose_name_plural': 'Quality Intervals',
                'db_table': 'QualityInterval',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='description', max_length=255)),
            ],
            options={
                'verbose_name': 'Rules',
                'verbose_name_plural': 'Rules',
                'db_table': 'Rule',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(db_column='weight')),
                ('indicator', models.ForeignKey(on_delete=None, to='indicator.Indicator')),
                ('stage', models.ForeignKey(on_delete=None, to='stage.Stage')),
            ],
            options={
                'verbose_name': 'Weights',
                'verbose_name_plural': 'Weights',
                'db_table': 'Weight',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
