# Generated by Django 2.2 on 2019-04-12 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='user',
            field=models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rule',
            name='weights',
            field=models.ManyToManyField(related_name='rule_weights', to='rule.Weight'),
        ),
    ]
