# Generated by Django 2.2 on 2019-06-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_auto_20190608_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='begin',
            field=models.IntegerField(db_column='threshold_begin'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='end',
            field=models.IntegerField(db_column='threshold_end'),
        ),
    ]
