# Generated by Django 2.2.2 on 2019-10-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_auto_20190725_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='quality',
            field=models.IntegerField(db_column='quality', max_length=10),
        ),
    ]
